apiVersion: v1
kind: Service
metadata:
  labels:
    app: pod-metadata
  name: pod-metadata-service
spec:
  ports:
  - port: 80 #change to 80
    protocol: TCP
    targetPort: 80 #change to 80
  selector:
    app: pod-metadata
  type: NodePort
